version: '3'
volumes:
  postgres_volume:
services:
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pvz
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data